[env]
TERM = xterm-256color

[window]
opacity = 0
dynamic_padding = false
startup_mode = 'Fullscreen'

[window.padding]
x = 0
y = 0

[font]
size = 15.0

[font.normal]
family = "Hack Nerd Font"

[selection]
save_to_clipboard = true
